### ISSUE TITLE
Migrate documentation site to GitHub Wiki

### ISSUE THREAD

**Issue by ruslan-kurchenko** [pkozuchowski/Apex-Opensource-Library#2]
First of all, @amorek  thank you for the library that you provide! I have used it several times on different projects. 🙏 

I would suggest you migrate your documentation site to GitHub Wiki and additional update the content there. You have added multiple items that we very useful, but they are not documented. If needed, I can try to find time to help you. Let me know!

**Comment by amorek** [comment]
Hi,
yeah I need to rewrite the page because it's too time-consuming to update the way it is now :) 
I have that in plans, but always lack time or will to work on it

**Comment by ruslan-kurchenko** [comment]
I see, @amorek . Let me know if I would help you.

**Comment by amorek** [comment]
On second thought, I will use wiki after all :D
